package fractional

import (
	"fmt"
	"math/big"
	"strings"
)

// GeneratePositionBetween returns a lexicographic fractional index between
// `before` and `after`. Either side may be "" to mean start/end.
// Examples:
//
//	("", "a0001")       -> "a0000"   (before first)
//	("a0001", "")       -> "a0002"   (after last)
//	("a0000", "a0002")  -> "a0001"   (between)
//	("a0000", "a0001")  -> "a00005"  (midpoint with more precision)
//
// See fractional_test.go.
func GeneratePositionBetween(before, after string) (string, error) {
	if before == "" && after != "" {
		return decrementPosition(after)
	}
	if before != "" && after == "" {
		return incrementPosition(before)
	}
	if before != "" && after != "" {
		return midpoint(before, after)
	}
	return "a0000", nil
}

// The digits after the letter prefix are a decimal FRACTION, not an integer:
// "a0001" < "a00015" < "a0002" lexicographically, exactly like 0.0001 <
// 0.00015 < 0.0002. All arithmetic below therefore pads operands to a common
// width first — at equal width, numeric order and lexicographic order agree,
// so same-width results are guaranteed to sort correctly against the inputs.

// padDigits right-pads a digit string with zeros to width l (appending zeros
// does not change the fraction's value).
func padDigits(d string, l int) string {
	return d + strings.Repeat("0", l-len(d))
}

// digitsInt parses a digit string as an integer (of its padded width).
func digitsInt(d string) (*big.Int, error) {
	n, ok := new(big.Int).SetString(d, 10)
	if !ok {
		return nil, fmt.Errorf("invalid position digits: %q", d)
	}
	return n, nil
}

// formatDigits renders n zero-padded to width l.
func formatDigits(n *big.Int, l int) string {
	s := n.String()
	return strings.Repeat("0", l-len(s)) + s
}

// incrementPosition: "a0000" -> "a0001"; "a9999" -> "b0000". Extended-
// precision inputs stay at their own width: "a00015" -> "a00016".
func incrementPosition(pos string) (string, error) {
	if pos == "" {
		return "a0000", nil
	}

	prefix := pos[0:1]
	digits := pos[1:]
	l := len(digits)

	num, err := digitsInt(digits)
	if err != nil {
		return "", err
	}
	num.Add(num, big.NewInt(1))

	if len(num.String()) > l {
		// All nines at this width — carry into the letter.
		if prefix[0] >= 'z' {
			return "", fmt.Errorf("position overflow: cannot increment beyond z9999")
		}
		return string(prefix[0]+1) + "0000", nil
	}

	return prefix + formatDigits(num, l), nil
}

// decrementPosition: "a0001" -> "a0000"; "a0000" -> previous letter + "9999".
// Extended-precision inputs stay at their own width: "a00015" -> "a00014".
func decrementPosition(pos string) (string, error) {
	if pos == "" {
		return "a0000", nil
	}

	prefix := pos[0:1]
	digits := pos[1:]
	l := len(digits)

	num, err := digitsInt(digits)
	if err != nil {
		return "", err
	}

	if num.Sign() == 0 {
		if prefix[0] <= 'A' {
			return "", fmt.Errorf("position underflow: cannot decrement below A0000")
		}
		return string(prefix[0]-1) + "9999", nil
	}

	num.Sub(num, big.NewInt(1))
	return prefix + formatDigits(num, l), nil
}

// midpoint: ("a0000","a0002") -> "a0001"; ("a0000","a0001") -> "a00005"
// (appends a digit when there's no gap at the common width).
func midpoint(before, after string) (string, error) {
	if before >= after {
		return "", fmt.Errorf("invalid positions: before (%s) must be < after (%s)", before, after)
	}

	beforePrefix := before[0:1]
	afterPrefix := after[0:1]

	if beforePrefix != afterPrefix {
		// Cross-prefix midpoints aren't generated by the normal insert paths.
		return "", fmt.Errorf("positions have different prefixes: %s and %s", before, after)
	}

	l := len(before) - 1
	if len(after)-1 > l {
		l = len(after) - 1
	}
	bp := padDigits(before[1:], l)
	ap := padDigits(after[1:], l)

	beforeNum, err := digitsInt(bp)
	if err != nil {
		return "", err
	}
	afterNum, err := digitsInt(ap)
	if err != nil {
		return "", err
	}

	gap := new(big.Int).Sub(afterNum, beforeNum)
	if gap.Sign() <= 0 {
		// Equal as fractions (e.g. "a0001" vs "a00010") — nothing fits between.
		return "", fmt.Errorf("no gap between positions %s and %s", before, after)
	}

	if gap.Cmp(big.NewInt(1)) > 0 {
		mid := new(big.Int).Add(beforeNum, new(big.Int).Rsh(gap, 1))
		return beforePrefix + formatDigits(mid, l), nil
	}

	// Adjacent at this width — extend precision by one digit.
	return beforePrefix + bp + "5", nil
}

// GetPositionAtIndex returns a position for inserting at index within positions.
func GetPositionAtIndex(positions []string, index int) (string, error) {
	if index < 0 {
		return "", fmt.Errorf("invalid index: %d (must be >= 0)", index)
	}

	if index > len(positions) {
		return "", fmt.Errorf("invalid index: %d (max is %d)", index, len(positions))
	}

	if index == 0 {
		if len(positions) == 0 {
			return "a0000", nil
		}
		return GeneratePositionBetween("", positions[0])
	}

	if index == len(positions) {
		return GeneratePositionBetween(positions[len(positions)-1], "")
	}

	return GeneratePositionBetween(positions[index-1], positions[index])
}

// NormalizePosition coerces a position string into the standard format.
func NormalizePosition(pos string) string {
	if pos == "" {
		return "a0000"
	}

	pos = strings.TrimSpace(pos)

	if len(pos) < 5 {
		return "a0000"
	}

	return pos
}
