package fractional

import (
	"fmt"
	"strings"
)

// GeneratePositionBetween returns a lexicographic fractional index between
// `before` and `after`. Either side may be "" to mean start/end.
// Examples:
//   ("", "a0001")       -> "a0000"   (before first)
//   ("a0001", "")       -> "a0002"   (after last)
//   ("a0000", "a0002")  -> "a0001"   (between)
//   ("a0000", "a0001")  -> "a00005"  (midpoint with more precision)
// See fractional_test.go.
func GeneratePositionBetween(before, after string) (string, error) {
	if before == "" && after != "" {
		return decrementPosition(after)
	}
	if before != "" && after == "" {
		return incrementPosition(before)
	}
	if before != "" && after != "" {
		return midpoint(before, after)
	}
	return "a0000", nil
}

// incrementPosition: "a0000" -> "a0001"; "a9999" -> "b0000".
func incrementPosition(pos string) (string, error) {
	if pos == "" {
		return "a0000", nil
	}

	prefix := pos[0:1]
	numStr := pos[1:]

	var num int
	fmt.Sscanf(numStr, "%d", &num)

	num++

	if num > 9999 {
		if prefix[0] >= 'z' {
			return "", fmt.Errorf("position overflow: cannot increment beyond z9999")
		}
		return string(prefix[0]+1) + "0000", nil
	}

	return fmt.Sprintf("%s%04d", prefix, num), nil
}

// decrementPosition: "a0001" -> "a0000"; "a0000" -> previous letter + "9999".
func decrementPosition(pos string) (string, error) {
	if pos == "" {
		return "a0000", nil
	}

	prefix := pos[0:1]
	numStr := pos[1:]

	var num int
	fmt.Sscanf(numStr, "%d", &num)

	num--

	if num < 0 {
		if prefix[0] <= 'A' {
			return "", fmt.Errorf("position underflow: cannot decrement below A0000")
		}
		return string(prefix[0]-1) + "9999", nil
	}

	return fmt.Sprintf("%s%04d", prefix, num), nil
}

// midpoint: ("a0000","a0002") -> "a0001"; ("a0000","a0001") -> "a00005"
// (appends a digit when there's no integer gap).
func midpoint(before, after string) (string, error) {
	if before >= after {
		return "", fmt.Errorf("invalid positions: before (%s) must be < after (%s)", before, after)
	}

	beforePrefix := before[0:1]
	afterPrefix := after[0:1]

	if beforePrefix == afterPrefix {
		beforeNum := 0
		afterNum := 0
		fmt.Sscanf(before[1:], "%d", &beforeNum)
		fmt.Sscanf(after[1:], "%d", &afterNum)

		if afterNum - beforeNum > 1 {
			midNum := (beforeNum + afterNum) / 2
			return fmt.Sprintf("%s%04d", beforePrefix, midNum), nil
		}

		// No integer gap — extend precision.
		return before + "5", nil
	}

	// Cross-prefix midpoints aren't generated by the normal insert paths.
	return "", fmt.Errorf("positions have different prefixes: %s and %s", before, after)
}

// GetPositionAtIndex returns a position for inserting at index within positions.
func GetPositionAtIndex(positions []string, index int) (string, error) {
	if index < 0 {
		return "", fmt.Errorf("invalid index: %d (must be >= 0)", index)
	}

	if index > len(positions) {
		return "", fmt.Errorf("invalid index: %d (max is %d)", index, len(positions))
	}

	if index == 0 {
		if len(positions) == 0 {
			return "a0000", nil
		}
		return GeneratePositionBetween("", positions[0])
	}

	if index == len(positions) {
		return GeneratePositionBetween(positions[len(positions)-1], "")
	}

	return GeneratePositionBetween(positions[index-1], positions[index])
}

// NormalizePosition coerces a position string into the standard format.
func NormalizePosition(pos string) string {
	if pos == "" {
		return "a0000"
	}

	pos = strings.TrimSpace(pos)

	if len(pos) < 5 {
		return "a0000"
	}

	return pos
}
